// 整集讨论区 —— 预先编写的高拟真社区评论（前端种子，无后端）。
// 按 videoId 组织；故意不按点赞数排好序，好让前端的「热度排序」肉眼可见地生效。
// 内容覆盖剧情解读 / 理论考据 / 吐槽三类，长短不一（长的用来演示折叠/展开）。

const DISCUSSION_SEED = {
  house_of_dragon_05: [
    {
      comment_id: 'hod05_d1',
      author: '高庭情报站',
      time: '3d',
      upvotes: 1243,
      text: '绿裙那一幕封神——Alicent 故意迟到、穿一身高庭战时召集色登场，这是她第一次当众向 Rhaenyra 宣战。全场只有 Rhaenyra 一个人当场听懂了，那个对视太狠了。',
    },
    {
      comment_id: 'hod05_d2',
      author: '绿党黑党都站',
      time: '2d',
      upvotes: 892,
      text: 'Criston 当众打死 Joffrey 不是单纯失控，是他意识到自己的秘密被对方捏在手里。从这一刻起他彻底倒向绿党，骑士的体面被他自己踩碎在婚礼地板上。',
    },
    {
      comment_id: 'hod05_d3',
      author: '红色婚礼幸存者',
      time: '1d',
      upvotes: 567,
      text: '这集婚礼死人比红色婚礼还突然，HBO 你能不能让人喘口气再发刀。',
    },
    {
      comment_id: 'hod05_d4',
      author: 'Daemon辩护律师',
      time: '2d',
      upvotes: 734,
      text: 'Daemon 杀妻那段镜头给得极克制——没拍过程，只拍结果。剧组故意让你既怀疑又拿不到实锤，而这种「可否认性」恰恰是 Daemon 这个角色的核心：他做尽脏事，却永远不留把柄。后面他对 Rhaenyra 说「你该自己去拿你想要的」，根就扎在这里。',
    },
    {
      comment_id: 'hod05_d5',
      author: '铁王座骨科',
      time: '18h',
      upvotes: 445,
      text: '注意 Viserys 这集咳血越来越频繁，铁王座割的伤口一直不愈合——马丁在用国王身体的腐烂，隐喻整个王国的腐烂。',
    },
    {
      comment_id: 'hod05_d6',
      author: '意难平专业户',
      time: '20h',
      upvotes: 389,
      text: 'Laenor 和 Joffrey 才是这集唯一的真爱，结果编剧开场没多久就给我刀了。',
    },
    {
      comment_id: 'hod05_d7',
      author: '箴言考据组',
      time: '1d',
      upvotes: 612,
      text: '这集标题「We Light the Way」就是 Hightower 家族的箴言——标题本身在剧透：这是 Hightower（绿党）正式登场掌权的一集。',
    },
    {
      comment_id: 'hod05_d8',
      author: '鸭鹅之约见证人',
      time: '15h',
      upvotes: 521,
      text: 'Rhaenyra 和 Laenor 婚前那段「鸭鹅之约」其实是全集最成熟的一段关系——两个被政治联姻摆布的年轻人，坦诚谈好「对外完婚、对内各自自由」。可惜 Criston 听不懂这套新规则，他要的是非黑即白的爱情或荣誉，悲剧由此开始。',
    },
    {
      comment_id: 'hod05_d9',
      author: 'Otto的头发',
      time: '12h',
      upvotes: 278,
      text: 'Otto 被撤了首相还阴魂不散，这老狐狸的政治生命力比龙还顽强。',
    },
    {
      comment_id: 'hod05_d10',
      author: '维斯特洛时事评论',
      time: '1d',
      upvotes: 701,
      text: '这集是全剧第一个真正的转折点：婚礼前大家还坐在同一张牌桌上，婚礼后绿黑彻底分裂。一场婚礼硬生生办成了开战仪式。',
    },
    {
      comment_id: 'hod05_d11',
      author: '配乐课代表',
      time: '8h',
      upvotes: 334,
      text: '小细节：绿裙登场时 Ramin Djawadi 把主题旋律改成了小调，配乐提前告诉你「气氛变了」。',
    },
    {
      comment_id: 'hod05_d12',
      author: '婚礼策划黑名单',
      time: '6h',
      upvotes: 256,
      text: '看完这集最大的感受：在维斯特洛参加婚礼，一定要先买好保险。',
    },
  ],
  house_of_dragon_s03e01: [
    {
      comment_id: 'hod_s03e01_d1',
      author: '蒂尔伯里旁听生',
      time: '1d',
      upvotes: 1386,
      text: '雷妮拉那句「女人的娇弱身躯／国王的意志和精神」明显在化用伊丽莎白一世 1588 年的蒂尔伯里演说。更妙的是原演说面对的也是舰队危机，这里台词落下就切进喉道海战，不只是借一句名言，连历史场景都一起搬过来了。',
    },
    {
      comment_id: 'hod_s03e01_d2',
      author: '龙石岛法务部',
      time: '20h',
      upvotes: 964,
      text: '杰斯让洛伦特「保护女王，包括防着她自己」这一段比吵架严重多了。他在临时发明一套高于女王命令的保护权：不开门是违抗君主，开门又可能被说成没有尽到誓言。洛伦特站在门口那几秒，等于被迫在女王本人和王权延续之间选边。',
    },
    {
      comment_id: 'hod_s03e01_d3',
      author: '海蛇船员甲',
      time: '18h',
      upvotes: 842,
      text: '喉道那段一直报六英寻、五英寻半、四英寻，真的比单纯喊「前方有礁石」紧张。测深绳就是没有声呐年代的实时雷达，科利斯能钻过窄道靠的不是主角光环，是他真的比追兵懂潮汐、暗流和自己这条船的吃水。',
    },
    {
      comment_id: 'hod_s03e01_d4',
      author: '龙比马快',
      time: '12h',
      upvotes: 517,
      text: '乌尔夫：「我要马干什么，我已经有龙了。」本集最无法反驳台词诞生。',
    },
    {
      comment_id: 'hod_s03e01_d5',
      author: '雾谷牧羊人',
      time: '15h',
      upvotes: 693,
      text: '很喜欢雷妮亚和偷羊贼这条线没有靠一声口令就瞬间认主。她一直在控制呼吸、降低姿态、重复安抚，偷羊贼也始终保留野性。这个过程让「得到一条龙」看起来像建立关系，而不是捡到武器。',
    },
    {
      comment_id: 'hod_s03e01_d6',
      author: '渡鸦车后勤组',
      time: '1d',
      upvotes: 748,
      text: '伊耿说自己是「一无所有之王」，王座是渡鸦粪，守护者还是被他嫌弃的拉里斯。嘴上把一切骂烂，现实却是他连逃命都离不开这辆车和拉里斯——王冠还在他头上，权力已经一点都够不着了。',
    },
    {
      comment_id: 'hod_s03e01_d7',
      author: '绿堡家庭调解员',
      time: '10h',
      upvotes: 604,
      text: '阿莉森承认「我们落到这一步都是我的错」，转头又劝伊蒙德去赫伦堡，还是她一贯的模式：情感上知道自己参与制造了灾难，行动上却只能继续用下一步政治安排补上一步政治安排。',
    },
    {
      comment_id: 'hod_s03e01_d8',
      author: '狭海地形课代表',
      time: '2d',
      upvotes: 1112,
      text: '这集终于拍清楚为什么喉道值得单独成为一场大战：它不是普通海面，而是黑水湾外的咽喉。大船在浅滩里不能随便转向，龙焰能烧甲板却不能把暗礁烧掉，所以舰队经验、地形和龙骑在这里谁也替代不了谁。',
    },
    {
      comment_id: 'hod_s03e01_d9',
      author: '三女儿王国公关',
      time: '9h',
      upvotes: 397,
      text: '洛哈尔最会的不是屠龙，是抢先给自己起「屠龙者」这个宣传标题。仗还没打完，战报标题已经写好了。',
    },
    {
      comment_id: 'hod_s03e01_d10',
      author: '沃马克斯护航队',
      time: '22h',
      upvotes: 1319,
      text: '结尾最痛的是杰斯前面把母亲锁住，理由是不能让王位继承断掉；后面他自己却骑沃马克斯冲进了最危险的位置。保护母亲、证明自己、救舰队三件事在他身上完全打结，最后每一个选择都把他推向海里。',
    },
    {
      comment_id: 'hod_s03e01_d11',
      author: '月舞低空摄影',
      time: '7h',
      upvotes: 461,
      text: '贝妮拉骑月舞俯冲那几段把龙战拍出了「友军也会怕」的感觉。龙是空中优势，但海面全是交错的桅杆、帆索和自己人，火力越大，协同失误的代价也越大。',
    },
    {
      comment_id: 'hod_s03e01_d12',
      author: '维斯特洛保险经纪',
      time: '5h',
      upvotes: 286,
      text: '本集生存提示：穿重甲上船之前，请先确认附近有没有人会突然问「你的盔甲有多重」。',
    },
  ],
};

export default DISCUSSION_SEED;
