import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import axios from 'axios';
import './RelationshipGraph.css';

// Family-tree data + portraits ship as static assets in client/public so the
// Vercel build renders without a backend. Snapshot is regenerated by
// server/scripts/build-graph-snapshots.js.
const SNAPSHOT_BASE = process.env.PUBLIC_URL || '';
const TREE_URL = `${SNAPSHOT_BASE}/relationship-graph/_family-tree.json`;

// Layout constants (svg "graph units" — pre-zoom). Tuned so 8-wide row 0 +
// 10-wide row 1 fit at 1× without overlap.
const COL_W = 150;
const ROW_H = 320;
const PORTRAIT_R = 38;
const COMPANION_R = 18;
const CANVAS_PAD = 100;
const CHILD_BUS_OFFSET = 110;   // vertical drop from parent row to the kid-bus bar
const SIBLING_BAR_OFFSET = -75; // sibling bar floats above the heads
const NAME_BLOCK_Y = PORTRAIT_R + 18;

// Conflict edge styling — color + dash by relation_kind. Tweak in CSS too.
const CONFLICT_STYLE = {
  enemy:  { className: 'rg-conf rg-conf-enemy' },
  ally:   { className: 'rg-conf rg-conf-ally' },
  secret: { className: 'rg-conf rg-conf-secret' },
  friend: { className: 'rg-conf rg-conf-friend' },
  blood:  { className: 'rg-conf rg-conf-blood' },
};

const ZOOM_MIN = 0.4;
const ZOOM_MAX = 3;

// ─── Layout: convert characters[] into pixel coords ─────────────────
function computeLayout(tree) {
  const positions = {};
  const byGen = {};
  for (const c of tree.characters) {
    (byGen[c.generation] ||= []).push(c);
  }
  for (const gen of Object.keys(byGen)) {
    byGen[gen].sort((a, b) => a.lineage_x - b.lineage_x);
  }
  // Find global max lineage_x to compute canvas width
  let maxX = 0, maxGen = 0;
  for (const c of tree.characters) {
    if (c.lineage_x > maxX) maxX = c.lineage_x;
    if (c.generation > maxGen) maxGen = c.generation;
  }

  for (const c of tree.characters) {
    positions[c.character_id] = {
      x: CANVAS_PAD + c.lineage_x * COL_W + COL_W / 2,
      y: CANVAS_PAD + c.generation * ROW_H + ROW_H / 2,
    };
  }

  const width = CANVAS_PAD * 2 + (maxX + 1) * COL_W;
  const height = CANVAS_PAD * 2 + (maxGen + 1) * ROW_H;
  return { positions, width, height };
}

// Group parent_child + parent_couple by parent set so we can draw one bracket
// per group (parent → bus bar → multiple kids).
function groupParentChildren(kinEdges) {
  const groups = new Map();
  for (const e of kinEdges) {
    let key, parents;
    if (e.kind === 'parent_couple') {
      key = e.parents.slice().sort().join('+');
      parents = e.parents.slice().sort();
    } else if (e.kind === 'parent_child') {
      key = e.from;
      parents = [e.from];
    } else {
      continue;
    }
    if (!groups.has(key)) groups.set(key, { parents, children: [] });
    groups.get(key).children.push(e.to);
  }
  return [...groups.values()];
}

// ─── Pure rendering helpers ─────────────────────────────────────────
function PillLabel({ x, y, text, kind = 'kin' }) {
  // Width is approximate — chinese chars are ~14px wide at the font size used.
  const padX = 10, padY = 5;
  const w = text.length * 16 + padX * 2;
  const h = 22;
  return (
    <g transform={`translate(${x}, ${y})`} className={`rg-pill rg-pill-${kind}`}>
      <rect x={-w / 2} y={-h / 2} width={w} height={h} rx={4} ry={4} />
      <text x={0} y={1} dominantBaseline="middle" textAnchor="middle">{text}</text>
    </g>
  );
}

function DragonGlyph({ size = 14 }) {
  const s = size / 22;
  return (
    <g transform={`scale(${s})`} className="rg-companion-glyph">
      <path d="M-6 -8 L-3.5 -10.5 M6 -8 L3.5 -10.5" />
      <path d="M-9 -3 C-10 -7 -6 -8 -3 -7 L3 -7 C6 -8 10 -7 9 -3 C10 0 8.5 4 5 6 L-5 6 C-8.5 4 -10 0 -9 -3 Z" />
      <circle cx="0" cy="-2" r="1.4" />
    </g>
  );
}

// Dragon attached to its rider — hangs below the name block.
function Companion({ data }) {
  if (!data) return null;
  const cy = NAME_BLOCK_Y + 32 + COMPANION_R;
  const clipId = `rg-comp-${data.character_id}`;
  return (
    <g className="rg-companion" transform={`translate(0, ${cy})`} aria-hidden>
      <defs>
        <clipPath id={clipId}>
          <circle cx={0} cy={0} r={COMPANION_R - 1} />
        </clipPath>
      </defs>
      <circle className="rg-companion-bg" r={COMPANION_R} />
      {data.portrait_url ? (
        <image
          href={data.portrait_url} xlinkHref={data.portrait_url}
          x={-(COMPANION_R - 1)} y={-(COMPANION_R - 1)}
          width={(COMPANION_R - 1) * 2} height={(COMPANION_R - 1) * 2}
          clipPath={`url(#${clipId})`} preserveAspectRatio="xMidYMid slice"
        />
      ) : (
        <DragonGlyph size={COMPANION_R * 1.4} />
      )}
      <text className="rg-companion-name" x={0} y={COMPANION_R + 11}>{data.display_name}</text>
    </g>
  );
}

function CharacterNode({ char, position, highlighted, focused, onClick }) {
  const clipId = `rg-clip-${char.character_id}`;
  const cls = [
    'rg-node',
    highlighted ? 'is-highlighted' : '',
    focused ? 'is-focused' : '',
    char.alive ? '' : 'is-dead',
  ].filter(Boolean).join(' ');
  return (
    <g
      className={cls}
      transform={`translate(${position.x}, ${position.y})`}
      onClick={(e) => { e.stopPropagation(); onClick(char.character_id); }}
    >
      <defs>
        <clipPath id={clipId}>
          <circle cx={0} cy={0} r={PORTRAIT_R - 2} />
        </clipPath>
      </defs>
      <circle className="rg-portrait-ring" r={PORTRAIT_R} />
      {char.portrait_url ? (
        <image
          href={char.portrait_url} xlinkHref={char.portrait_url}
          x={-(PORTRAIT_R - 2)} y={-(PORTRAIT_R - 2)}
          width={(PORTRAIT_R - 2) * 2} height={(PORTRAIT_R - 2) * 2}
          clipPath={`url(#${clipId})`} preserveAspectRatio="xMidYMid slice"
        />
      ) : (
        <text className="rg-initial" y={6}>{(char.display_name || '').slice(0, 1)}</text>
      )}

      {char.epithet && (
        <g className="rg-epithet" transform={`translate(0, ${-PORTRAIT_R - 4})`}>
          <rect x={-32} y={-10} width={64} height={20} rx={2} ry={2} />
          <text y={1} dominantBaseline="middle">{char.epithet}</text>
        </g>
      )}

      <text className="rg-name-zh" y={NAME_BLOCK_Y}>{char.display_name}</text>
      <text className="rg-name-en" y={NAME_BLOCK_Y + 16}>{char.name_en}</text>
      {!char.alive && (
        <text className="rg-died" y={NAME_BLOCK_Y + 32}>已故</text>
      )}

      <Companion data={char.companion} />
    </g>
  );
}

// ─── Kin edge layer ─────────────────────────────────────────────────
function MarriageEdge({ a, b, label, sameRow }) {
  if (sameRow) {
    // horizontal bar between two same-row portraits, "夫妻" pill mid-bar
    const y = a.y;
    const x1 = Math.min(a.x, b.x) + PORTRAIT_R;
    const x2 = Math.max(a.x, b.x) - PORTRAIT_R;
    const mid = (x1 + x2) / 2;
    return (
      <g className="rg-kin rg-kin-marriage">
        <line x1={x1} y1={y} x2={x2} y2={y} />
        <PillLabel x={mid} y={y} text={label} kind="kin" />
      </g>
    );
  }
  // cross-row marriage (Daemon-Rhaenyra) — diagonal line, pill in middle
  const mx = (a.x + b.x) / 2;
  const my = (a.y + b.y) / 2;
  // start/end on the rim of each circle along the line direction
  const dx = b.x - a.x, dy = b.y - a.y;
  const dist = Math.sqrt(dx * dx + dy * dy);
  const ux = dx / dist, uy = dy / dist;
  const x1 = a.x + ux * PORTRAIT_R, y1 = a.y + uy * PORTRAIT_R;
  const x2 = b.x - ux * PORTRAIT_R, y2 = b.y - uy * PORTRAIT_R;
  return (
    <g className="rg-kin rg-kin-marriage rg-kin-cross-gen">
      <line x1={x1} y1={y1} x2={x2} y2={y2} />
      <PillLabel x={mx} y={my} text={label} kind="kin" />
    </g>
  );
}

function SiblingEdge({ a, b, label }) {
  // Bracket *above* the two heads. Used only for siblings whose parents
  // aren't visible (would be redundant otherwise — already filtered out
  // server-side).
  const yBar = a.y + SIBLING_BAR_OFFSET;
  const xL = Math.min(a.x, b.x);
  const xR = Math.max(a.x, b.x);
  return (
    <g className="rg-kin rg-kin-sibling">
      <line x1={a.x} y1={a.y - PORTRAIT_R} x2={a.x} y2={yBar} />
      <line x1={b.x} y1={b.y - PORTRAIT_R} x2={b.x} y2={yBar} />
      <line x1={xL} y1={yBar} x2={xR} y2={yBar} />
      <PillLabel x={(xL + xR) / 2} y={yBar} text={label} kind="kin" />
    </g>
  );
}

function ParentBracketEdge({ parents, children, positions }) {
  // Skip if any participant is missing a position (defensive — shouldn't happen)
  for (const p of parents) if (!positions[p]) return null;
  for (const c of children) if (!positions[c]) return null;

  const parentPts = parents.map(p => positions[p]);
  // Anchor point: midpoint of the parent(s). For single parent, use their
  // own (x, y+r). For couple, midpoint of the marriage bar.
  let anchorX, anchorY;
  if (parents.length === 1) {
    anchorX = parentPts[0].x;
    anchorY = parentPts[0].y + PORTRAIT_R;
  } else {
    anchorX = (parentPts[0].x + parentPts[1].x) / 2;
    anchorY = parentPts[0].y;  // both same row; same-row marriage bar
  }

  const childPts = children.map(c => positions[c]);
  // Skip drawing if parent(s) and any child are in the same row (e.g.,
  // Otto→Alicent in our merged layout): would be a sideways edge that
  // looks broken. The user explicitly accepted this as an aesthetic
  // tradeoff for compactness.
  const allChildrenBelow = childPts.every(p => p.y > anchorY + 10);
  if (!allChildrenBelow) return null;

  const busY = anchorY + CHILD_BUS_OFFSET;
  const xs = childPts.map(p => p.x);
  const xL = Math.min(...xs);
  const xR = Math.max(...xs);

  return (
    <g className="rg-kin rg-kin-parent">
      {/* trunk: vertical from parent anchor down to bus */}
      <line x1={anchorX} y1={anchorY} x2={anchorX} y2={busY} />
      {/* bus: horizontal bar spanning all kids' columns (extends to anchor if needed) */}
      <line x1={Math.min(xL, anchorX)} y1={busY} x2={Math.max(xR, anchorX)} y2={busY} />
      {/* legs: vertical drop from bus to each kid's top */}
      {childPts.map((p, i) => (
        <line key={i} x1={p.x} y1={busY} x2={p.x} y2={p.y - PORTRAIT_R} />
      ))}
      {/* "子女" pill on the trunk */}
      <PillLabel x={anchorX} y={(anchorY + busY) / 2} text="子女" kind="kin" />
    </g>
  );
}

// ─── Conflict overlay ───────────────────────────────────────────────
function ConflictEdge({ from, to, kind, relation, positions }) {
  const a = positions[from];
  const b = positions[to];
  if (!a || !b) return null;
  const dx = b.x - a.x, dy = b.y - a.y;
  const dist = Math.sqrt(dx * dx + dy * dy) || 1;
  const ux = dx / dist, uy = dy / dist;
  const x1 = a.x + ux * PORTRAIT_R, y1 = a.y + uy * PORTRAIT_R;
  const x2 = b.x - ux * PORTRAIT_R, y2 = b.y - uy * PORTRAIT_R;
  const mx = (x1 + x2) / 2, my = (y1 + y2) / 2;
  const style = CONFLICT_STYLE[kind] || CONFLICT_STYLE.enemy;
  return (
    <g className={style.className}>
      <line x1={x1} y1={y1} x2={x2} y2={y2} />
      {relation && (
        <g className="rg-conf-label" transform={`translate(${mx}, ${my})`}>
          <rect x={-relation.length * 8 - 6} y={-11} width={relation.length * 16 + 12} height={22} rx={3} ry={3} />
          <text dominantBaseline="middle" textAnchor="middle">{relation}</text>
        </g>
      )}
    </g>
  );
}

// ─── Pan / zoom hook ────────────────────────────────────────────────
function useViewport(graphSize, viewportRef) {
  const [view, setView] = useState({ scale: 1, tx: 0, ty: 0 });
  const dragRef = useRef(null);
  const pinchRef = useRef(null);

  // Initial fit when graph size or viewport changes (only first time per open).
  const fit = useCallback(() => {
    const el = viewportRef.current;
    if (!el || !graphSize.width) return;
    const { clientWidth: vw, clientHeight: vh } = el;
    const sx = vw / graphSize.width;
    const sy = vh / graphSize.height;
    const scale = Math.max(ZOOM_MIN, Math.min(ZOOM_MAX, Math.min(sx, sy) * 0.95));
    const tx = (vw - graphSize.width * scale) / 2;
    const ty = (vh - graphSize.height * scale) / 2;
    setView({ scale, tx, ty });
  }, [graphSize.width, graphSize.height, viewportRef]);

  useEffect(() => { fit(); }, [fit]);

  // Pan-only: keep current scale, smoothly center the given graph point.
  // Used by the time-driven focus to bring the on-screen character into view.
  const centerOn = useCallback((gx, gy, targetScale) => {
    const el = viewportRef.current;
    if (!el || gx == null || gy == null) return;
    const vw = el.clientWidth, vh = el.clientHeight;
    setView(v => {
      const s = targetScale != null
        ? Math.max(ZOOM_MIN, Math.min(ZOOM_MAX, targetScale))
        : v.scale;
      return { scale: s, tx: vw / 2 - gx * s, ty: vh / 2 - gy * s };
    });
  }, [viewportRef]);

  const onWheel = useCallback((e) => {
    if (!viewportRef.current) return;
    e.preventDefault();
    const rect = viewportRef.current.getBoundingClientRect();
    const mx = e.clientX - rect.left;
    const my = e.clientY - rect.top;
    setView(v => {
      const factor = e.deltaY < 0 ? 1.12 : 1 / 1.12;
      const next = Math.max(ZOOM_MIN, Math.min(ZOOM_MAX, v.scale * factor));
      const ratio = next / v.scale;
      return { scale: next, tx: mx - (mx - v.tx) * ratio, ty: my - (my - v.ty) * ratio };
    });
  }, [viewportRef]);

  const onMouseDown = useCallback((e) => {
    if (e.button !== 0) return;
    dragRef.current = { x: e.clientX, y: e.clientY };
  }, []);

  const onMouseMove = useCallback((e) => {
    if (!dragRef.current) return;
    const dx = e.clientX - dragRef.current.x;
    const dy = e.clientY - dragRef.current.y;
    dragRef.current = { x: e.clientX, y: e.clientY };
    setView(v => ({ ...v, tx: v.tx + dx, ty: v.ty + dy }));
  }, []);

  const onMouseUp = useCallback(() => { dragRef.current = null; }, []);

  // touch: 1 finger = pan, 2 fingers = pinch zoom
  const onTouchStart = useCallback((e) => {
    if (e.touches.length === 1) {
      dragRef.current = { x: e.touches[0].clientX, y: e.touches[0].clientY };
      pinchRef.current = null;
    } else if (e.touches.length === 2) {
      const [a, b] = e.touches;
      pinchRef.current = {
        d: Math.hypot(a.clientX - b.clientX, a.clientY - b.clientY),
        cx: (a.clientX + b.clientX) / 2,
        cy: (a.clientY + b.clientY) / 2,
      };
      dragRef.current = null;
    }
  }, []);

  const onTouchMove = useCallback((e) => {
    if (e.touches.length === 2 && pinchRef.current) {
      e.preventDefault();
      const [a, b] = e.touches;
      const d = Math.hypot(a.clientX - b.clientX, a.clientY - b.clientY);
      const factor = d / pinchRef.current.d;
      pinchRef.current.d = d;
      const rect = viewportRef.current.getBoundingClientRect();
      const mx = pinchRef.current.cx - rect.left;
      const my = pinchRef.current.cy - rect.top;
      setView(v => {
        const next = Math.max(ZOOM_MIN, Math.min(ZOOM_MAX, v.scale * factor));
        const ratio = next / v.scale;
        return { scale: next, tx: mx - (mx - v.tx) * ratio, ty: my - (my - v.ty) * ratio };
      });
    } else if (e.touches.length === 1 && dragRef.current) {
      const dx = e.touches[0].clientX - dragRef.current.x;
      const dy = e.touches[0].clientY - dragRef.current.y;
      dragRef.current = { x: e.touches[0].clientX, y: e.touches[0].clientY };
      setView(v => ({ ...v, tx: v.tx + dx, ty: v.ty + dy }));
    }
  }, [viewportRef]);

  const onTouchEnd = useCallback(() => {
    dragRef.current = null;
    pinchRef.current = null;
  }, []);

  const zoomBy = useCallback((factor) => {
    setView(v => {
      const el = viewportRef.current;
      if (!el) return v;
      const cx = el.clientWidth / 2, cy = el.clientHeight / 2;
      const next = Math.max(ZOOM_MIN, Math.min(ZOOM_MAX, v.scale * factor));
      const ratio = next / v.scale;
      return { scale: next, tx: cx - (cx - v.tx) * ratio, ty: cy - (cy - v.ty) * ratio };
    });
  }, [viewportRef]);

  return {
    view, fit, centerOn,
    onWheel, onMouseDown, onMouseMove, onMouseUp,
    onTouchStart, onTouchMove, onTouchEnd,
    zoomIn: () => zoomBy(1.25), zoomOut: () => zoomBy(1 / 1.25),
  };
}

// ─── Main component ─────────────────────────────────────────────────
export default function RelationshipGraph({ videoId, videoRef }) {
  const [tree, setTree] = useState(null);
  const [focusList, setFocusList] = useState(null);
  const [open, setOpen] = useState(false);
  const [hasNews, setHasNews] = useState(false);
  const [scanKey, setScanKey] = useState(0);
  const [error, setError] = useState(null);
  const [highlighted, setHighlighted] = useState(null);
  const [focused, setFocused] = useState(null);
  const viewportRef = useRef(null);

  // load tree once on first open
  useEffect(() => {
    if (!open || tree) return;
    let cancelled = false;
    axios.get(TREE_URL, { timeout: 8000 })
      .then(r => { if (!cancelled) setTree(r.data); })
      .catch(err => { if (!cancelled) setError(err?.message || String(err)); });
    return () => { cancelled = true; };
  }, [open, tree]);

  // load scene-focus map keyed on videoId; fail-quiet if not present
  useEffect(() => {
    if (!videoId) { setFocusList(null); return; }
    let cancelled = false;
    const url = `${SNAPSHOT_BASE}/relationship-graph/_scene-focus-${encodeURIComponent(videoId.replace(/\.[^.]+$/, ''))}.json`;
    axios.get(url, { timeout: 5000 })
      .then(r => { if (!cancelled) setFocusList(r.data); })
      .catch(() => { if (!cancelled) setFocusList(null); });
    return () => { cancelled = true; };
  }, [videoId]);

  useEffect(() => {
    if (!open) return;
    const onKey = (e) => { if (e.key === 'Escape') setOpen(false); };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open]);

  // reset state when video changes (in case the demo bumps to a different show)
  useEffect(() => { setHighlighted(null); setFocused(null); }, [videoId]);

  // Time-driven focus: poll currentTime every 600ms, look up the dominant
  // character for that moment, and update local state. Cheap binary search
  // through the merged ranges keeps polling work negligible even at 458
  // entries.
  useEffect(() => {
    if (!open || !focusList || !videoRef?.current) return;
    let raf = 0;
    let lastHero = null;
    const tick = () => {
      const v = videoRef.current;
      if (v && !v.paused) {
        const t = v.currentTime;
        // Linear scan with start-cache would be enough; binary search just to
        // be safe if the list ever grows.
        let lo = 0, hi = focusList.length - 1, hit = null;
        while (lo <= hi) {
          const m = (lo + hi) >> 1;
          const r = focusList[m];
          if (t < r.start) hi = m - 1;
          else if (t >= r.end) lo = m + 1;
          else { hit = r; break; }
        }
        const heroId = hit ? hit.hero_id : null;
        if (heroId !== lastHero) {
          lastHero = heroId;
          setFocused(heroId);
        }
      }
      raf = window.setTimeout(tick, 600);
    };
    tick();
    return () => clearTimeout(raf);
  }, [open, focusList, videoRef]);

  const layout = useMemo(() => tree ? computeLayout(tree) : null, [tree]);
  const parentGroups = useMemo(
    () => tree ? groupParentChildren(tree.kin_edges) : [],
    [tree],
  );

  const conflictByChar = useMemo(() => {
    const m = new Map();
    if (!tree) return m;
    for (const e of tree.conflict_edges) {
      (m.get(e.from) || m.set(e.from, []).get(e.from)).push(e);
      (m.get(e.to) || m.set(e.to, []).get(e.to)).push(e);
    }
    return m;
  }, [tree]);

  const graphSize = layout ? { width: layout.width, height: layout.height } : { width: 0, height: 0 };
  const viewport = useViewport(graphSize, viewportRef);

  // When the video moves to a new focal character, gently re-center the view
  // on them. Only fires if the user isn't actively dragging.
  useEffect(() => {
    if (!open || !focused || !layout) return;
    const pos = layout.positions[focused];
    if (!pos) return;
    viewport.centerOn(pos.x, pos.y);
  }, [focused, layout, open, viewport]);

  const openFocus = useCallback(() => {
    setOpen(true);
    setHasNews(false);
    setScanKey(k => k + 1);
  }, []);

  const close = useCallback(() => setOpen(false), []);

  const onCharClick = useCallback((id) => {
    setHighlighted(prev => prev === id ? null : id);
  }, []);

  const clearHighlight = useCallback((e) => {
    if (e.target === e.currentTarget) setHighlighted(null);
  }, []);

  const activeConflicts = highlighted ? (conflictByChar.get(highlighted) || []) : [];

  return (
    <div className={`rg-root ${open ? 'is-viewing' : ''}`}>
      <div className="rg-cine-bar" />
      <div className="rg-cine-bar rg-cine-bar-bottom" />

      <div className="rg-hud-edge">
        <div
          className={`rg-hud-icon ${hasNews ? 'has-news' : ''}`}
          onClick={openFocus}
          title="关系"
        >
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round">
            <circle cx="8.5" cy="8" r="2.6" />
            <path d="M3.6 18c.5-2.6 2.6-4.4 4.9-4.4s4.4 1.8 4.9 4.4" />
            <circle cx="16" cy="9.5" r="2.2" />
            <path d="M13.5 18.5c.4-2.1 2.1-3.6 4-3.6s3.6 1.5 4 3.6" />
            <line x1="9.5" y1="11" x2="14" y2="11" strokeDasharray="1 2" />
          </svg>
        </div>
      </div>

      <div className={`rg-focus-overlay ${open ? 'open' : ''}`}>
        <div className="rg-scrim" onClick={close} />
        <div className="rg-tree-card">
          <div className="rg-scan-line" key={scanKey} />
          <button className="rg-close" onClick={close} title="关闭 (Esc)">×</button>

          <header className="rg-tree-header">
            <div className="rg-tree-title-zh">
              {tree?.title_zh}
              {tree?.subtitle_zh ? <span className="rg-tree-subtitle-zh">{tree.subtitle_zh}</span> : null}
            </div>
            <div className="rg-tree-title-en">
              <span>{tree?.title_en}</span>
              {tree?.subtitle_en ? <span className="rg-tree-subtitle-en">{tree.subtitle_en}</span> : null}
            </div>
          </header>

          <div className="rg-zoom-controls">
            <button onClick={viewport.zoomIn} title="放大">＋</button>
            <button onClick={viewport.zoomOut} title="缩小">−</button>
            <button onClick={viewport.fit} title="适配">⟲</button>
          </div>

          <div
            className="rg-tree-viewport"
            ref={viewportRef}
            onWheel={viewport.onWheel}
            onMouseDown={viewport.onMouseDown}
            onMouseMove={viewport.onMouseMove}
            onMouseUp={viewport.onMouseUp}
            onMouseLeave={viewport.onMouseUp}
            onTouchStart={viewport.onTouchStart}
            onTouchMove={viewport.onTouchMove}
            onTouchEnd={viewport.onTouchEnd}
            onDoubleClick={viewport.fit}
            onClick={clearHighlight}
          >
            {error && <div className="rg-error">关系图加载失败：{error}</div>}
            {tree && layout && (
              <svg
                className="rg-tree-svg"
                width={layout.width}
                height={layout.height}
                style={{
                  transform: `translate(${viewport.view.tx}px, ${viewport.view.ty}px) scale(${viewport.view.scale})`,
                  transformOrigin: '0 0',
                }}
              >
                {/* kin layer (always shown) */}
                <g className="rg-kin-layer">
                  {parentGroups.map((g, i) => (
                    <ParentBracketEdge
                      key={`pg-${i}`}
                      parents={g.parents}
                      children={g.children}
                      positions={layout.positions}
                    />
                  ))}
                  {tree.kin_edges
                    .filter(e => e.kind === 'marriage')
                    .map((e, i) => {
                      const a = layout.positions[e.from];
                      const b = layout.positions[e.to];
                      if (!a || !b) return null;
                      return (
                        <MarriageEdge
                          key={`mar-${i}`}
                          a={a} b={b}
                          label={e.label}
                          sameRow={a.y === b.y}
                        />
                      );
                    })}
                  {tree.kin_edges
                    .filter(e => e.kind === 'sibling')
                    .map((e, i) => {
                      const a = layout.positions[e.from];
                      const b = layout.positions[e.to];
                      if (!a || !b) return null;
                      return <SiblingEdge key={`sib-${i}`} a={a} b={b} label={e.label} />;
                    })}
                </g>

                {/* conflict overlay (only when a character is highlighted) */}
                {highlighted && (
                  <g className="rg-conflict-layer">
                    {activeConflicts.map((e, i) => (
                      <ConflictEdge
                        key={`conf-${i}`}
                        from={e.from} to={e.to}
                        kind={e.kind} relation={e.relation}
                        positions={layout.positions}
                      />
                    ))}
                  </g>
                )}

                {/* portrait layer last so circles draw above edges */}
                <g className="rg-node-layer">
                  {tree.characters.map(c => (
                    <CharacterNode
                      key={c.character_id}
                      char={c}
                      position={layout.positions[c.character_id]}
                      highlighted={highlighted === c.character_id}
                      focused={focused === c.character_id}
                      onClick={onCharClick}
                    />
                  ))}
                </g>
              </svg>
            )}
          </div>

          <footer className="rg-tree-legend">
            <span className="rg-legend-hint">点击角色 → 显示该角色的剧情冲突线</span>
          </footer>
        </div>
      </div>
    </div>
  );
}
